#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config border_width         2
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Floating mode for some Applications

bspc rule -a Thunar state=floating rectangle=650x500+1050+100

# Auto Start Applications
sxhkd &
$HOME/.config/polybar/launch.sh --forest
nitrogen --restore
nm-applet --indicator &
dunst &
