#! /bin/sh

# Startups
$HOME/.config/bspwm/autostart

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d 1 2 3 4

bspc config border_width         2
bspc config border_radius       10

bspc config window_gap          5
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


bspc config normal_border_color "#3c3836"
bspc config focused_border_color "#458588"

# Floating Apps
declare -a floatingApps=(
  Lxappearance 
  Blueman-manager
  Nm-connection-editor 
  Gparted 
  Xarchiver 
  Cheese
  Thunar
  Pavucontrol
  mpv
  Brave:Dialog Brave:Pop-up
)
for i in ${floatingApps[@]}; do
    bspc rule -a $i state=floating focus=on follow=on; done

declare -a floatingCust=(
  *:*:Picture-in-picture
  *:Toolkit:Picture-in-Picture
)
for i in ${floatingCust[@]}; do
	bspc rule -a $i state=floating sticky=on follow=off focus=on \
    rectangle=500x350+1366+50; done
