#!/bin/sh

VOLUME=$(pamixer --get-volume-human)

# Notify
notify_user() {
  notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "Volume: " -h int:value:"$VOLUME"
}

case $1 in
    "--inc")
        pamixer --increase 2 && notify_user
        ;;
    "--dec")
        pamixer --decrease 2 && notify_user
        ;;
    "--toggle")
        pamixer --toggle-mute && notify_user
        ;;
    *)
        echo "options: --inc --dec --toggle"
esac
